New features added
fralx/LimeReport pull request #461
Opened 2024-06-06 22:34 UTC by yanis60

Hi,
I've added some new features, such as

1- Border for page.
2- GroupHeader has a sortfieldname property.
3- Guide lines for alignement.
4- Improved context menu.

2024-06-18 21:30 UTC, Jihadist commented on 3rdparty/object_script.QtZint.Release
Please do not include your local files

2024-06-19 11:02 UTC, yanis60 commented
i pulled the latest commit from original repo before pushing it

2024-06-20 09:58 UTC, fralx commented on 3rdparty/object_script.QtZint.Release
@yanis60 Hi,  Your commit contains auto generated files such as:
[3rdparty/object_script.QtZint.Release](https://github.com/fralx/LimeReport/pull/461/files#diff-c679fc16ab3101ac5e25ab06c530a2bcd24a1e2fed1b3751dc312f8341953667)
[3rdparty/win32/release/moc/moc_predefs.h](https://github.com/fralx/LimeReport/pull/461/files#diff-56730d8afa6a51742f13ac5ad8bdb5bd765d14c5e13a7973c03dc6d47056ae3c)
and so on. Remove it please

2024-06-22 06:56 UTC, Jihadist commented on CMakeLists.txt
Please do not delete cmakelists :)

2024-06-22 06:56 UTC, Jihadist commented on OKQmAj.json
Should be deleted

2024-06-22 06:57 UTC, Jihadist commented on limereport/win32/debug/moc/mocinclude.opt
There are your local files here

2024-06-22 08:43 UTC, yanis60 commented on CMakeLists.txt
sorry i'm not good in github stuffs, i know just how to commit and push and pull :)

2024-06-23 18:50 UTC, fralx commented on .vscode/settings.json
Hi. This file have to be removed

2024-06-23 18:59 UTC, fralx commented on Nouveau dossier/lrbasedesignintf.cpp
I guess this folder  [Nouveau dossier](https://github.com/fralx/LimeReport/pull/461/files#diff-0fd63145849afefd4de7e771295a8d653cf4e7a3091b10ba76fc5a4c7c7669f5) should be removed as redundant

2024-06-23 19:07 UTC, yanis60 commented on .vscode/settings.json
i apology if some files are commited

2024-06-26 13:09 UTC, fralx commented on limereport/win32/release/moc/mocinclude.opt
The files in this folder limereport/win32 are autogerated

2024-06-27 08:21 UTC, fralx reviewed
Hi! Some files need to be removed

2024-06-27 08:21 UTC, fralx commented on lrdview/release/lrdview.exe
This file have to removed  from the  commit

2024-06-27 08:21 UTC, fralx commented on lrdview/win32/debug/moc/mocinclude.opt
This file have to removed from the commit

2024-06-27 08:21 UTC, fralx commented on lrdview/win32/release/moc/mocinclude.opt
This file have to removed from  the commit

2024-06-27 08:21 UTC, fralx commented on translations/limereport_ar.ts
if you didn't change the translation, you shouldn't include it in the commit

2024-06-27 08:21 UTC, fralx commented on translations/limereport_es.ts
if you didn't change the translation, you shouldn't include it in the commit

2024-06-27 08:21 UTC, fralx commented on translations/limereport_zh.ts
if you didn't change the translation, you shouldn't include it in the commit

2024-06-27 08:21 UTC, fralx commented on translations/limereport_ru.ts
if you didn't change the translation, you shouldn't include it in the commit

2024-06-27 08:21 UTC, fralx commented on translations/limereport_ru.qm
if you didn't change the translation, you shouldn't include it in the commit

2024-06-27 08:21 UTC, fralx commented on translations/limereport_pl.ts
if you didn't change the translation, you shouldn't include it in the commit

2024-06-27 08:21 UTC, fralx commented on translations/limereport_fr.ts
if you didn't change the translation, you shouldn't include it in the commit

2024-06-27 08:21 UTC, fralx commented on include/lrrenderengine.h
semicolon is redundant

2024-06-27 08:21 UTC, fralx commented on .vscode/settings.json
This file still exists in the commit

2024-06-27 08:21 UTC, fralx commented on README.md
This changes should be rollback

2024-06-28 10:10 UTC, fralx commented on translations/limereport_ar.ts
You should't delete this file you have to just not include it in commit. The thanslations files have to return back.

2024-06-28 11:53 UTC, yanis60 commented on translations/limereport_ar.ts
i'm really sorry for those mistakes this is becasuse of .gitignore i guess

2024-06-30 12:05 UTC, Jihadist requested changes
Although it looks much better, but it had not completed yet

2024-06-30 12:05 UTC, Jihadist commented on CMakeLists.txt
Please do not commit changes that does not really change anything.

2024-06-30 12:05 UTC, Jihadist commented on README.md
Also here

2024-06-30 12:05 UTC, Jihadist commented on common.pri
> -    unix|win32: LIBS *= -L$$PWD/3rdparty/easyprofiler/build/bin/ -leasy_profiler
Also here

2024-07-06 18:53 UTC, yanis60 commented on common.pri
> -    unix|win32: LIBS *= -L$$PWD/3rdparty/easyprofiler/build/bin/ -leasy_profiler
just spaces that has been removed here

2024-07-18 16:46 UTC, fralx reviewed
Please explain why sort field name property is needed?

2024-07-19 08:00 UTC, closed without merging